### PR TITLE
Add config file option.

### PR DESCRIPTION
**Pull request by slowbro**
For 42wim/matterircd#63

### CODE REVIEW

**Comment by 42wim** [comment]
Thanks! 
Looks good, but I'm wondering why you changed `logger` to `Logger` in main.go ?

**Comment by slowbro** [comment]
Ah yes... I supposed that was needed to access to logger from the config
package but then ended up just setting it in main().. I can change that
back tonight :)

**Comment by 42wim** [comment]
Yes please:)
The rest is fine and can be merged!

**Comment by slowbro** [comment]
There we go. I rebased it all into one commit, too, and also added a `Logger.Infof` in `config` to output the config loaded info:

$ ./matterircd -config matterircd.toml
INFO[2017-11-27T10:11:23-08:00] Loaded config from matterircd.toml            module=matterircd
INFO[2017-11-27T10:11:23-08:00] Running version 0.15.0                        module=matterircd
INFO[2017-11-27T10:11:23-08:00] Listening on 127.0.0.1:6666                   module=matterircd

**Comment by slowbro** [comment]
Sorry, one last try! I had accidentally removed the `// backwards compatible` section. re-added.

**Comment by slowbro** [comment]
Found a bug.. not ready for merge. `cfg` doesn't seem to be available in the `go func()` subsections. Investigating.

**Comment by 42wim** [comment]
Ok, I'll wait, don't have time to help you at the moment though :(

**Comment by slowbro** [comment]
No worries. I actually fixed it in 979ae99... I was re-initializing cfg (:=) instead of just using it since it was defined in vars. :)

**Comment by 42wim** [comment]
Thanks a lot!

**Pull request merged**
