### PR TITLE
Do not split message on newlines

### PR DESCRIPTION
**Pull request by 42wim**
This fixes https://github.com/42wim/matterircd/issues/480 and as a bonus also fixes https://github.com/42wim/matterircd/issues/426 as this is now just 1 big message for irc

### CODE REVIEW

**Comment by 42wim** [comment]
@hloeung any feedback, am I missing something that maybe will break? :)

**Comment by hloeung** [comment]
Might be IRC line limits. Also a large message with a mixture of text and code blocks where texts with empty lines aren't removed? Probably not a big deal though.

**Comment by 42wim** [comment]
The IRC line limits are not an issue, we're splitting the lines before sending them on IRC
I've also add another commit to also check for the codeblock starting on other lines.

wrt to empty lines I think the advantages outweigh the possible disavantage of some few empty lines when mixing codeblocks with non-code blocks.

It can be optimized later though, but not a showstopper for this change.

**Comment by hloeung** [comment]
@42wim https://github.com/42wim/matterircd/pull/483 merge into this one

**Pull request merged**
