### PR TITLE
handle fileids/pasted images

### PR DESCRIPTION
**Pull request by maxandersen**
Handle fileids / pasted images

DONT MERGE - I know this issue should be fixed properly in matterbridge first, but just wanted to get verification this approach would be valid fix.

Why:

 * there is no message sent when images or files sent

This change addreses the need by:

 * doing the same as was done for filenames, but fileid instead
   and using direct links rather than public ones.

Solves #82

### CODE REVIEW

**Comment by maxandersen** [comment]
You can run `docker run -p 6667:6667 maxandersen/matterircd:latest -bind 0.0.0.0:6667` to try this fix btw.

you should see things like: 
`<maxandersen>	download file - https://chat.openshift.io/api/v3/files/3soce66dbbrq9ncehanab16eka/get`

when user maxandersen shares a file.

When clicking you'll need to be logged in to get to the files - I don't know a good way around that.

**Comment by furai** [comment]
IMO that's the proper way, you shouldn't be able to share files with users outside of mattermost. 
Another thing - IMO the function should check for the file extensions. For example just give the link to view PNG and not download it.

**Comment by maxandersen** [comment]
@furai i don't know mattermost api well enough but on first glance any of the api calls available in the client to get file info failed so I only have the "raw" url.

**Comment by faljse** [comment]
Thx, this patch really improves the experience for our irc clients.

During testing we discovered these Issues
- Message is delivered to clients correctly, but doesn't get recorded in the log/scrollback
- m.Client.ApiUrl doesn't reflect the mattermost "SiteURL" in my case
- Images are downloaded by the browser; it would prefer my browser to display the Image instead

**Comment by maxandersen** [comment]
> Message is delivered to clients correctly, but doesn't get recorded in the log/scrollback

Not sure what you mean here ? what log/scrollback are you expecting the message to be recorded ? 

> m.Client.ApiUrl doesn't reflect the mattermost "SiteURL" in my case

Any chance you know which combo of properties would work for you ?

> Images are downloaded by the browser; i would prefer my browser to display the Image instead

yeah, if we could figure out how to get the extended metadata of the link it should be possible. But i couldn't find a method that wouldn't result in errors yet.

**Comment by faljse** [comment]
> what log/scrollback are you expecting the message to be recorded ?

matterircd provides a "scrollback" command for users not permanently connected via irc:
https://github.com/42wim/matterircd#mattermost-user-commands
> Any chance you know which combo of properties would work for you ?

The "SiteURL" as configured in Mattermost config.json  or an additional parameter to matterircd would work

**Comment by 42wim** [comment]
Thanks for your work! I've fixed part of this in master. (public links)

If you got private links working feel free to open PR against https://github.com/42wim/mm-go-irckit and https://github.com/42wim/matterbridge

**Comment by 42wim** [comment]
@faljse I've just added support for public links in SCROLLBACK and SEARCH (in master)

**Pull request closed without merging**
