### PR TITLE
Allow adding or removing reactions

### PR DESCRIPTION
**Pull request by hloeung**
This is to specific posts/messages, using the same syntax as you would via the Mattermost UI (+:emoji_name: and -:emoji_name:).

    |20:22 <hloeung> @@e9jdm8qwxtdq88nb949i6tcp6y +:coffee:
    |20:22 <hloeung> added reaction: coffee [↪@@e9jdm8qwxtdq88nb949i6tcp6y]
    |20:22 <hloeung> @@e9jdm8qwxtdq88nb949i6tcp6y -:coffee:
    |20:22 <hloeung> removed reaction: coffee [↪@@e9jdm8qwxtdq88nb949i6tcp6y]

One for you @devec0 but too late ;)

### CODE REVIEW

**Comment by axinojolais** [comment]
How do you get the ID of a message ?

**Comment by hloeung** [comment]
> How do you get the ID of a message ?

Only works with single messages, not replies to threads at the moment. We could have matterircd show both thread/parent ID and message IDs, will have to think more about this one.

**Comment by 42wim** [comment]
@hloeung cool!
I suggest calling the methods AddReaction and RemoveReaction to be consistent with the ReactionAdd and ReactionRemove events

**Comment by hloeung** [comment]
> @hloeung cool!
> I suggest calling the methods AddReaction and RemoveReaction to be consistent with the ReactionAdd and ReactionRemove events

Will rename.

Also, do you prefer I push up additional commits to these WIP/draft changes or commit --amend and push --force?

**Comment by hloeung** [comment]
|17:12 <hloeung> @@001 +:+1:
    |17:12 <hloeung> added reaction: +1 [001]
    |17:15 <hloeung> @@001 -:+1:
    |17:16 <hloeung> removed reaction: +1 [001]

**Comment by hloeung** [comment]
|21:48 <hloeung> Testing one
    |21:48 <hloeung> Testing two
    |21:48 <hloeung> @@66dfpgmkztfrtetuwhx5wbmcty +:+1:
    |21:48 <hloeung> Testing three
    |21:48 <hloeung> Testing four
    |21:48 <hloeung> added reaction: +1 [↪66dfp…]

Produces this:

SfYuEyYy12

**Comment by 42wim** [comment]
> Also, do you prefer I push up additional commits to these WIP/draft changes or commit --amend and push --force?

Whatever matches your workflow best. 
I you have useful commits (with correct naming convention) I won't squash them.

**Comment by hloeung** [comment]
Going to separate out 4678d3be0638856549bc405d33e6454a2e01c64b to a different PR.

**Comment by 42wim** [comment]
thx, will look/test it this weekend

**Comment by 42wim** [comment]
sorry for the delay

**Comment by hloeung** [comment]
No problems at all. Thanks!

**Comment by furai** [comment]
Hmm, missing documentation for this in prefixcontext.md?

**Comment by hloeung** [comment]
> Hmm, missing documentation for this in prefixcontext.md?

Ah, apologies. Here it is https://github.com/42wim/matterircd/pull/405

**Comment by furai** [comment]
Thanks!

**Pull request merged**
