### PR TITLE
Fallback to use API for getting channel data when not in the cache

### PR DESCRIPTION
**Pull request by hloeung**
Fixes https://github.com/42wim/matterircd/issues/479

### CODE REVIEW

**Comment by hloeung** [comment]
Pushed a fix which also fixes this:
```
ERRO[2022-11-04T09:39:21Z] didn't find channel ggy... (ggy...): channel not found  module=matterircd
```

Likely due to the same issue where page limit isn't obeyed so not present in the cache. This is not really a fix but more a workaround. Untested, will do more testing tomorrow (it's late here).

**Comment by hloeung** [comment]
https://github.com/42wim/matterircd/pull/491, I think we should still have this as a fallback, but your call.

**Comment by 42wim** [comment]
Yes a fallback is a good idea, will add this after https://github.com/matterbridge/matterclient/pull/1 merges

**Comment by 42wim** [comment]
Can you rebase on master? vendor has been updated

**Comment by hloeung** [comment]
Sure, working on that now.

Apologies for the mess with the various PRs. Will be more careful and neater next time.

**Comment by hloeung** [comment]
Ok, done. Also pushed up a drive-by fix from https://github.com/42wim/matterircd/pull/491/

**Comment by 42wim** [comment]
> Apologies for the mess with the various PRs. Will be more careful and neater next time.

No apologies needed though :)
LGTM

**Comment by hloeung** [comment]
Thank you!

**Pull request merged**
