### PR TITLE
Add http.ProxyFromEnvironment to use default env var like in net/http…

### PR DESCRIPTION
**Pull request by ryarnyah**
Add standard http client proxy possibility to matterircd like DefaultTransport in net/http/transport.go.

=> To report on matterbridge/matterclient

### CODE REVIEW

**Comment by ryarnyah** [comment]
Edit: I'm sorry, i wasn't testing with the right env var.... this PR can be closed.

**Comment by ryarnyah** [comment]
Edit: I'm sorry, i tried again and my PR solve proxy connection.

**Comment by 42wim** [comment]
@ryarnyah  Thanks!

I see you made the PR also at matterbridge, but closed it.
If you got it working could you open it at matterbridge again? 
I can't merge it here because matterircd vendors matterbridge.

**Comment by ryarnyah** [comment]
Done https://github.com/42wim/matterbridge/pull/162

**Comment by 42wim** [comment]
merged in matterbridge

**Pull request closed without merging**
