### PR TITLE
MVS alternative

### PR DESCRIPTION
**Pull request by dogboat**
This pull request presents an idea for alternative solution to the ["MVS problem"](https://github.com/42wim/matterircd/issues/24). Essentially, the user client tracks message counts per channel for messages they send; on the receiving side, they see if that message exists in their data structure, and if so, doesn't process it.

Some notes:

- It might be useful to add some sort of eviction timer to the cache, so that in the unlikely event an IRC user sends a message but doesn't receive it back, the structure doesn't end up with data that hangs around forever.
- A lot of work is done creating/deleting maps every time a message is sent; perhaps it'd be better to not do that, or put some sort of timer on that as well.
- I'm new to golang, so there's a very good chance I don't know what I'm doing, and I'm very sorry about that.

Good idea, bad idea? It seems to work for us. Hopefully there's at least something useful contained in here.

Thanks so much!

### CODE REVIEW

**Comment by 42wim** [comment]
First and foremost thanks for looking for a better solution. 
Your idea looks good, but it adds quite some complexity.

I'm wondering about your issue with MVS, are those things visible for you in mattermost ? 
Would something else like maybe zero-width space (http://www.fileformat.info/info/unicode/char/200b/index.htm) be an option to try ?

**Comment by dogboat** [comment]
Haha yeah, it definitely is complex, especially if further modifications need to be made (e.g. adding and synching goroutines to evict entries, icky!).

The major issue this solves is actually for a user who connects via Adium. In Adium, the MVS displays as a "cannot find" character. Additionally, the MVS does appear in OSX notifications when using the Mattermost (Electron) client. And finally, links sent by users using IRC don't allow you to just click them -- the MVS is parsed as part of the URL.

The zero-width space might be a good solution, depending on how the various clients/notifications render them. Perhaps those wouldn't interfere with URLs by nature of being whitespace characters. I'd definitely be willing to try it, and that's much simpler!

**Comment by 42wim** [comment]
Could you checkout and build from the 'zws' branch ? 
This has the MVS changed to the zero-width space. Let me know if this looks better :)

**Comment by dogboat** [comment]
Works really well! The only thing is, clicking URLs still doesn't work, that character is still detected as part of the URL. :(

Could you perhaps append a space and then the zws? And then check for that? I'd imagine that would then handle URLs properly... Or maybe Mattermost's URL parsing is what needs to be fixed.

Thanks!

**Comment by 42wim** [comment]
Ok, try again :-)

**Comment by dogboat** [comment]
Fantastic, that seems to resolve the all issues we've noticed. You can definitely decline this one in favor of zws, if that's what you want to do. Thanks so much!

**Comment by 42wim** [comment]
Great, thanks for testing,I'll change the MVS then to space+ZWS
I'll not be implementing this PR for now

**Pull request closed without merging**
