### PR TITLE
Support Mattermost 10.0.0

### LINKED ISSUE #584: Broken on Mattermost 10?
Hi,

I recently upgraded to Mattermost 10 and matterircd no longer seems to work.  My irc bot can no longer connect.  I don't have any other useful info, unfortunately, but I can try to debug if someone gives me pointers.

Regards,

Dianne.

### PR DESCRIPTION
**Pull request by dfskoll**
This is  a simple patch that enables support for Mattermost 10.

Closes  #584

### CODE REVIEW

**Review by hloeung — APPROVED** [review]
LGTM

**Comment by dfskoll** [comment]
Thanks!

**Comment by micah** [comment]
I wonder if there should be a release tag for this support?

**Comment by dfskoll** [comment]
Since there is a workaround (https://github.com/42wim/matterircd/pull/541) I don't think it's worth making a release just for this fix.

**Comment by micah** [comment]
On 2024-10-18 08:15:28, Dianne Skoll wrote:
> Since there is a workaround (https://github.com/42wim/matterircd/pull/541) I don't think it's worth making a release just for this fix.

Ah thanks for that, I didn't notice that option!

**Comment by kkofler** [comment]
IMHO, there should be a new release for this change. At least as long as `ignoreserverversion` is `false` by default.

I have now set `ignoreserverversion=true` in my deployment, and I will keep it that way, at least as long as `matterircd` does not make timely releases for new Mattermost versions. (This one has been sitting there for 2 months now.) But at that point, if the recommendation is for everyone to just enable `ignoreserverversion`, I wonder why there is a version check at all and why it is enabled by default.

**Pull request merged**
